[Task] Update tronador docs with submodule mkdocs SA 5303
stakater/tronador-docs pull request #20
Opened 2024-05-24 20:25 UTC by RSAK56

# Description
1. Updated support docs with mkdocs theme common submodule
2. Shifted vocabulary to vale and removed vocabulary submodule
Fixes # (issue)
UI/UX
# Type of change
Enhancement
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] UI/UX modification
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-26 21:21 UTC, karl-johan-grahn requested changes
Don't add generic logos, they should be added through the common theme

2024-05-27 09:18 UTC, RSAK56 commented
> Don't add generic logos, they should be added through the common theme

Updated the footer logos to theme common, logo's apart from them will need to be updated when provided by design teams. Each doc will have a one separate logo in the header. So keeping the header ones in the override.

2024-05-27 14:57 UTC, karl-johan-grahn requested changes

2024-05-27 14:57 UTC, karl-johan-grahn commented on content/config_file.md
> -    Their values must also be `{{APPLICATION_IMAGE_NAME}}` and `{{APPLICATION_IMAGE_TAG}}` respectively. These keys will be replaced with values provided from the cluster task in your CI pipeline tha
notes need to be indented, otherwise they won't display properly

2024-05-27 20:44 UTC, karl-johan-grahn approved these changes

2024-05-27 20:44 UTC, merged